### PR TITLE
Add release process

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Fixes https://github.com/giantswarm/inago/issues/9

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
@giantswarm/cena RFR

**Comment by Nesurion** [comment]
releasing does include updating homebrew things doesn't it?

**Comment by zeisss** [comment]
LGTM

no docker or homebrew stuff for now.

**Comment by Nesurion** [comment]
@zeisss ack. LGTM

**Pull request merged**
