### PR TITLE
Add example functions

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Fixes https://github.com/giantswarm/inago/issues/77

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
screen shot 2016-03-11 at 17 01 26

We get cool examples in `godoc` now with this :dancer:

@zeisss thoughts?

**Comment by zeisss** [comment]
Love it :) LGTM

**Comment by Nesurion** [comment]
Nice! LGTM

**Comment by JosephSalisbury** [comment]
I'll probably find a few more little functions that have this pattern.

**Comment by JosephSalisbury** [comment]
But I didn't - merging .

**Pull request merged**
