### PR TITLE
trim trailing slash from group

### LINKED ISSUE #210: If a group name is suffixed with '/', remove the slash
I use tab completion a lot, it would be nice if I didn't have to backspace

### PR DESCRIPTION
**Pull request by xh3b4sd**
fixes #210 

See tests. 

RFR @JosephSalisbury @Nesurion @zeisss

### CODE REVIEW

**Comment by Nesurion** [comment]
LGTM

**Comment by JosephSalisbury** [comment]
My original idea was just to do this in the `cli` package - why do we want it in the controller?

**Comment by xh3b4sd** [comment]
Makes no sense to me in the CLI. Would be needed in every damn place. Anyway, the "fix" is only a PR away.

**Comment by JosephSalisbury** [comment]
Works for me for now either way.

**Pull request merged**
