### PR TITLE
Bump k8s versions to 1.2.4

### PR DESCRIPTION
**Pull request by hectorj2f**
This version will upgrade k8s to the latest version and remove deprecated flags.

### CODE REVIEW

**Comment by puja108** [comment]
I was using 1.2.0 just to show rolling updates in the inago blog post and example

**Comment by puja108** [comment]
@hectorj2f we should maybe bump directly to 1.2.4

**Comment by hectorj2f** [comment]
ping @xh3b4sd @JosephSalisbury, do you know anything about this error ?

**Comment by JosephSalisbury** [comment]
I do not. Will attempt to have a look today.

**Comment by xh3b4sd** [comment]
@hectorj2f what is "this" error?

**Comment by hectorj2f** [comment]
@xh3b4sd https://travis-ci.org/giantswarm/inago/jobs/129942807

**Comment by xh3b4sd** [comment]
This looks to me like a travis error. Maybe that had issues executing jobs. Try to build a new travis CI job.

**Comment by hectorj2f** [comment]
@JosephSalisbury  I'll go and merge this PR

**Comment by JosephSalisbury** [comment]
https://github.com/giantswarm/inago/issues/249 as a ticket for fixing that integration test, i've assigned myself

**Pull request merged**
